name:                CodeFormatter
version:             0.1.0.0
github:              "tmgross/CodeFormatter"
license:             BSD-3-Clause
author:              "Tim Gross"
maintainer:          "tmgross8@gmail.com"
copyright:           "2024 Tim Gross"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tmgross/CodeFormatter#readme>

dependencies:
- base >= 4.7 && < 5
- HUnit >= 1.6
- parsec
- text
- mtl
- filepath
- directory
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  CodeFormatter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CodeFormatter

tests:
  CodeFormatter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CodeFormatter
